GET http://localhost:7071/api/createAzureBatchJob
    ?name=Stephen

GET http://localhost:7071/api/GetRatings



    

POST http://localhost:7071/api/createAzureBatchJob HTTP/1.1
content-type: application/json

{
    "tasksToRun": 100,
    "loopsMultiplier": 100,
    "displayName": "PieCalculatorJobfromAzureFunctionApp",
    "priority": 700,
    "maxTaskBatch": 100
} 
    
POST http://localhost:7071/api/getJobStatus HTTP/1.1
content-type: application/json

{
    "verbose":true,
    "jobID": "ef783b3f-b20b-4cf3-a12e-748b23b00347"
} 

POST http://localhost:7071/api/getJobStatus HTTP/1.1
content-type: application/json

{
    "verbose":false,
    "jobID": "78120e81-c28e-41f5-9f2d-28eb6d396521"
} 


POST http://localhost:7071/api/deleteJob HTTP/1.1
content-type: application/json

{
    "name":"Stephen",
    "jobID": "be85f9fd-0b68-42dc-97a5-0eb79bb79916"
    } 

POST http://localhost:7071/api/deleteMatchingJobs HTTP/1.1
content-type: application/json

{
    "displayNameMatch":"PieCalculatorJobfromAzureFunctionApp",
    "jobState": "completed"
    } 











